export const data = [
  {
    id: "1",
    title: "LinkedUp",
    desc: "Created a web parser using selenium and python. It logs into linkedin for you and searches for whatever jobs you want. It then goes to the jobs page and scrapes linked in for them and saves the data into a JSON file.",
    img: "./slitherSlither.jpg",
    backgroundColor: "#cb7c7a",
    technologies: [
      "devicon-selenium-original colored",
      "devicon-python-plain-wordmark",
      "devicon-vscode-plain-wordmark colored",
    ],
    git: "https://github.com/ramather/Selenium-LInkedIn-WebCrawler",
    link: "https://github.com/ramather/LinkedUp",
  },
  {
    id: "2",
    title: "Macrolator",
    desc: "Created a an application that calculates your daily caloric and macronutrient needs. Please not that it is not 100% scientifically acurate. I merely got the formula from some health website and wanted to practice react.",
    img: "./calculatorscreen.jpg",
    backgroundColor: "#36a18b",
    technologies: [
      "devicon-react-original-wordmark",
      "devicon-html5-plain-wordmark colored",
      "devicon-css3-plain-wordmark colored",
    ],
    git: "https://github.com/ramather/MacroCalculator",
    link: "https://gracious-roentgen-05a50d.netlify.app",
  },
  {
    id: "3",
    title: "Pokegen",
    desc: "I created this using the PokeAPI. You search for a pokemon and it generates a card using data from the API. It will change color based on the pokemon's type. Super fun to make. Learned how to us CSS grid in the process.",
    img: "./pokemon.jpg",
    backgroundColor: "#cda35f",
    technologies: [
      "devicon-react-original-wordmark",
      "devicon-html5-plain-wordmark colored",
      "devicon-css3-plain-wordmark colored",
      "devicon-sass-original colored",
    ],
    git: "https://github.com/ramather/pokemon-fun",
    link: "https://blissful-hopper-f34929.netlify.app/",
  },
];
